{
 "title": "DTR RethinkDB Stats",
 "description": "Dashboard for Prometheus collected RethinkDB stats",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "label_values(dtr_up, instance)" },
   {
    "name": "server",
    "query": "label_values(dtr_server_client_connections{instance=~\"$instance.*\"}, replica)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(dtr_tablereplica_metadata_bytes{instance=~\"$instance.*\", replica=~\"$server.*\"}, db)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values(dtr_tablereplica_metadata_bytes{instance=~\"$instance.*\", replica=~\"$server.*\", db=~\"$database.*\"}, table)"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Client connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "dtr_cluster_client_connections" }
   ]
  },
  {
   "title": "Cluster clients active",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "dtr_cluster_clients_active" }
   ]
  },
  {
   "title": "Server client connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(dtr_server_client_connections{replica=~\"$server.*\"})"
    }
   ]
  },
  {
   "title": "Server client connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(dtr_server_clients_active{replica=~\"$server.*\"})"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Queries/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dtr_cluster_queries_per_second", "legendFormat": "Queries/Sec" }
   ]
  },
  {
   "title": "Read docs/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dtr_cluster_docs_per_second{operation=~\"read\"}",
     "legendFormat": "Read/Sec"
    }
   ]
  },
  {
   "title": "Written docs/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dtr_cluster_docs_per_second{operation=~\"written\"}",
     "legendFormat": "Written/Sec"
    }
   ]
  },
  {
   "title": "Total servers(replicas)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "dtr_server_count" }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * dtr_server_health_count{health=\"healthy\"}/ ignoring(health) dtr_server_count"
    }
   ]
  },
  {
   "title": "Total tables",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "dtr_table_count" }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Server io/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dtr_server_queries_per_second{replica=~\"$server.*\"}",
     "legendFormat": "{{replica}} Queries/sec"
    },
    {
     "expr": "dtr_server_docs_per_second{replica=~\"$server.*\", operation=\"read\"}",
     "legendFormat": "{{replica}} Read/sec"
    },
    {
     "expr": "dtr_server_docs_per_second{replica=~\"$server.*\", operation=\"written\"}",
     "legendFormat": "{{replica}} Write/sec"
    }
   ]
  },
  {
   "title": "Queries total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dtr_server_queries_total{replica=~\"$server.*\"}",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Read Docs total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dtr_server_docs_total{replica=~\"$server.*\", operation=~\"read\"}",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  {
   "title": "Written Docs total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dtr_server_docs_total{replica=~\"$server.*\", operation=~\"written\"}",
     "legendFormat": "{{replica}}"
    }
   ]
  },
  { "title": "Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Table disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dtr_tablereplica_data_bytes{replica=~\"$server.*\", db=~\"$database.*\", table=~\"$table.*\"}",
     "legendFormat": "{{replica}}.{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Table cache usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dtr_tablereplica_cache_bytes{replica=~\"$server.*\", db=~\"$database.*\", table=~\"$table.*\"}",
     "legendFormat": "{{replica}}.{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Table metadata usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dtr_tablereplica_metadata_bytes{replica=~\"$server.*\", db=~\"$database.*\", table=~\"$table.*\"}",
     "legendFormat": "{{replica}}.{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Table prealocated usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dtr_tablereplica_preallocated_bytes{replica=~\"$server.*\", db=~\"$database.*\", table=~\"$table.*\"}",
     "legendFormat": "{{replica}}.{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Table garbage usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dtr_tablereplica_garbage_bytes{replica=~\"$server.*\", db=~\"$database.*\", table=~\"$table.*\"}",
     "legendFormat": "{{replica}}.{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Disk Read Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dtr_tablereplica_io{replica=~\"$server.*\", db=~\"$database.*\", table=~\"$table.*\", operation=\"read\"}",
     "legendFormat": "{{replica}}.{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Disk Written Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dtr_tablereplica_io{replica=~\"$server.*\", db=~\"$database.*\", table=~\"$table.*\", operation=\"written\"}",
     "legendFormat": "{{replica}}.{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Read Docs/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dtr_tablereplica_docs_per_second{replica=~\"$server.*\", db=~\"$database.*\", table=~\"$table.*\", operation=\"read\"}",
     "legendFormat": "{{replica}}.{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Written Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dtr_tablereplica_docs_per_second{replica=~\"$server.*\", db=~\"$database.*\", table=~\"$table.*\", operation=\"written\"}",
     "legendFormat": "{{replica}}.{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Server Read Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dtr_table_docs_per_second{db=~\"$database.*\", table=~\"$table.*\", operation=\"read\"}",
     "legendFormat": "{{db}}.{{table}}"
    }
   ]
  },
  {
   "title": "Server Written Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dtr_table_docs_per_second{db=~\"$database.*\", table=~\"$table.*\", operation=\"written\"}",
     "legendFormat": "{{db}}.{{table}}"
    }
   ]
  }
 ]
}